"""Pylyra: symbolic differential geometry tools built on SymPy."""

from .core import (
    Connection,
    ConnectionStrategy,
    CurvatureStrategy,
    Down,
    DownIndex,
    FixedConnectionStrategy,
    Index,
    IndexedTensor,
    LyraConnectionStrategy,
    LyraCurvatureStrategy,
    Manifold,
    Metric,
    NO_LABEL,
    SpaceTime,
    Tensor,
    TensorFactory,
    TensorSpace,
    Up,
    UpIndex,
    D,
    U,
    d,
    example_indexing,
    greek,
    u,
)

__all__ = [
    "Connection",
    "ConnectionStrategy",
    "CurvatureStrategy",
    "Down",
    "DownIndex",
    "FixedConnectionStrategy",
    "Index",
    "IndexedTensor",
    "LyraConnectionStrategy",
    "LyraCurvatureStrategy",
    "Manifold",
    "Metric",
    "NO_LABEL",
    "SpaceTime",
    "Tensor",
    "TensorFactory",
    "TensorSpace",
    "Up",
    "UpIndex",
    "D",
    "U",
    "d",
    "example_indexing",
    "greek",
    "u",
]

__version__ = "0.1.0"
